Better readme
michalvankodev/metaframer pull request #1
Opened 2024-05-17 21:13 UTC by Samuell1

2024-05-17 21:26 UTC, michalvankodev requested changes

2024-05-17 21:26 UTC, michalvankodev commented on README.md
> +- **Broad Compatibility:** Works with a wide array of image formats and video editing software.
It just generates images. This doesn't make sense.

2024-05-17 21:26 UTC, michalvankodev commented on README.md
> +- **Real-Time Preview:** Edit and see changes in real-time.
There is no preview

2024-05-17 21:26 UTC, michalvankodev commented on README.md
> +- **Batch Processing:** Apply consistent frames to multiple images at once.
```suggestion
- **Batch Processing:** Create consistent frames to multiple images at once.
```

We are not applying or editing the original images. `metaframer` only creates the frame for the images.

2024-05-17 21:26 UTC, michalvankodev commented on README.md
> +- **User-Friendly Interface:** Accessible for users of all skill levels.
Ehm ehm, This is only a CLI tool

2024-05-17 21:26 UTC, michalvankodev commented on README.md
> +To get started with Metaframer, follow these simple installation steps:
Missing `TODO`

2024-05-18 06:38 UTC, Samuell1 commented on README.md
> +- **User-Friendly Interface:** Accessible for users of all skill levels.
```suggestion
```

2024-05-18 06:38 UTC, Samuell1 commented on README.md
> +To get started with Metaframer, follow these simple installation steps:
```suggestion
To get started with Metaframer, follow these simple installation steps:

<!-- TODO -->
```

2024-05-18 06:39 UTC, Samuell1 commented on README.md
> +- **Real-Time Preview:** Edit and see changes in real-time.
```suggestion
```

2024-05-18 06:39 UTC, Samuell1 commented on README.md
> +- **Broad Compatibility:** Works with a wide array of image formats and video editing software.
```suggestion
```

2024-06-24 06:13 UTC, closed without merging